TWILIO_SID = "ACf2f7d194d327d5765657dae960b00be9"
TWILIO_AUTH = "042690137875bb64abf52d8c"
TWILIO_FROM_NUMBER = "+91 8096432075"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 465
SMTP_USER = "ksankar8096@gmail.com"
SMTP_PASS = "sjpg kuga hwnb maba"